/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gles_internal_GLES10ExtPipeline */

#ifndef _Included_gles_internal_GLES10ExtPipeline
#define _Included_gles_internal_GLES10ExtPipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gles_internal_GLES10ExtPipeline
 * Method:    nGLES10ExtClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10ExtPipeline_nGLES10ExtClassInit
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES10ExtPipeline
 * Method:    nGLQueryMatrixxOES
 * Signature: ([II[II)I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES10ExtPipeline_nGLQueryMatrixxOES___3II_3II
  (JNIEnv *, jclass, jintArray, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES10ExtPipeline
 * Method:    nGLQueryMatrixxOES
 * Signature: (Ljava/nio/IntBuffer;ILjava/nio/IntBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES10ExtPipeline_nGLQueryMatrixxOES__Ljava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jobject, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
