/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gles_internal_GLES30Pipeline */

#ifndef _Included_gles_internal_GLES30Pipeline
#define _Included_gles_internal_GLES30Pipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLES30ClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLES30ClassInit
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLReadBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLReadBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDrawRangeElements
 * Signature: (IIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDrawRangeElements__IIIIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDrawRangeElements
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDrawRangeElements__IIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLTexImage3D
 * Signature: (IIIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLTexImage3D__IIIIIIIIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLTexImage3D
 * Signature: (IIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLTexImage3D__IIIIIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLTexSubImage3D
 * Signature: (IIIIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLTexSubImage3D__IIIIIIIIIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLTexSubImage3D
 * Signature: (IIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLTexSubImage3D__IIIIIIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLCopyTexSubImage3D
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLCopyTexSubImage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLCompressedTexImage3D
 * Signature: (IIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLCompressedTexImage3D__IIIIIIIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLCompressedTexImage3D
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLCompressedTexImage3D__IIIIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLCompressedTexSubImage3D
 * Signature: (IIIIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLCompressedTexSubImage3D__IIIIIIIIIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLCompressedTexSubImage3D
 * Signature: (IIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLCompressedTexSubImage3D__IIIIIIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGenQueries
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGenQueries__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGenQueries
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGenQueries__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDeleteQueries
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDeleteQueries__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDeleteQueries
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDeleteQueries__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLIsQuery
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES30Pipeline_nGLIsQuery
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLBeginQuery
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLBeginQuery
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLEndQuery
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLEndQuery
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetQueryiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetQueryiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetQueryiv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetQueryiv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetQueryObjectuiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetQueryObjectuiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetQueryObjectuiv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetQueryObjectuiv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUnmapBuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES30Pipeline_nGLUnmapBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetBufferPointerv
 * Signature: (II)Ljava/nio/Buffer;
 */
JNIEXPORT jobject JNICALL Java_gles_internal_GLES30Pipeline_nGLGetBufferPointerv
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDrawBuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDrawBuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDrawBuffers
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDrawBuffers__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniformMatrix2x3fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniformMatrix2x3fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniformMatrix2x3fv
 * Signature: (IIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniformMatrix2x3fv__IIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniformMatrix3x2fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniformMatrix3x2fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniformMatrix3x2fv
 * Signature: (IIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniformMatrix3x2fv__IIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniformMatrix2x4fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniformMatrix2x4fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniformMatrix2x4fv
 * Signature: (IIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniformMatrix2x4fv__IIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniformMatrix4x2fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniformMatrix4x2fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniformMatrix4x2fv
 * Signature: (IIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniformMatrix4x2fv__IIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniformMatrix3x4fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniformMatrix3x4fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniformMatrix3x4fv
 * Signature: (IIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniformMatrix3x4fv__IIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniformMatrix4x3fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniformMatrix4x3fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniformMatrix4x3fv
 * Signature: (IIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniformMatrix4x3fv__IIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLBlitFramebuffer
 * Signature: (IIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLBlitFramebuffer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLRenderbufferStorageMultisample
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLRenderbufferStorageMultisample
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLFramebufferTextureLayer
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLFramebufferTextureLayer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLMapBufferRange
 * Signature: (IIII)Ljava/nio/Buffer;
 */
JNIEXPORT jobject JNICALL Java_gles_internal_GLES30Pipeline_nGLMapBufferRange
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLFlushMappedBufferRange
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLFlushMappedBufferRange
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLBindVertexArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLBindVertexArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDeleteVertexArrays
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDeleteVertexArrays__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDeleteVertexArrays
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDeleteVertexArrays__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGenVertexArrays
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGenVertexArrays__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGenVertexArrays
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGenVertexArrays__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLIsVertexArray
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES30Pipeline_nGLIsVertexArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetIntegeriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetIntegeriv
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetIntegeriv0
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetIntegeriv0
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLBeginTransformFeedback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLBeginTransformFeedback
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLEndTransformFeedback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLEndTransformFeedback
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLBindBufferRange
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLBindBufferRange
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLBindBufferBase
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLBindBufferBase
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLTransformFeedbackVaryings
 * Signature: (I[Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLTransformFeedbackVaryings
  (JNIEnv *, jclass, jint, jobjectArray, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetTransformFeedbackVarying
 * Signature: (III[II[II[II[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetTransformFeedbackVarying__III_3II_3II_3II_3BI
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint, jintArray, jint, jintArray, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetTransformFeedbackVarying
 * Signature: (II[II[II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES30Pipeline_nGLGetTransformFeedbackVarying__II_3II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetTransformFeedbackVarying
 * Signature: (IILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES30Pipeline_nGLGetTransformFeedbackVarying__IILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLVertexAttribIPointerBounds
 * Signature: (IIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLVertexAttribIPointerBounds
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLVertexAttribIPointer
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLVertexAttribIPointer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetVertexAttribIiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetVertexAttribIiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetVertexAttribIiv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetVertexAttribIiv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetVertexAttribIuiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetVertexAttribIuiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetVertexAttribIuiv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetVertexAttribIuiv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLVertexAttribI4i
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLVertexAttribI4i
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLVertexAttribI4ui
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLVertexAttribI4ui
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLVertexAttribI4iv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLVertexAttribI4iv__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLVertexAttribI4iv
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLVertexAttribI4iv__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLVertexAttribI4uiv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLVertexAttribI4uiv__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLVertexAttribI4uiv
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLVertexAttribI4uiv__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetUniformuiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetUniformuiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetUniformuiv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetUniformuiv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetFragDataLocation
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES30Pipeline_nGLGetFragDataLocation
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniform1ui
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniform1ui
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniform2ui
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniform2ui
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniform3ui
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniform3ui
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniform4ui
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniform4ui
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniform1uiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniform1uiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniform1uiv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniform1uiv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniform2uiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniform2uiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniform2uiv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniform2uiv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniform3uiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniform3uiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniform3uiv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniform3uiv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniform4uiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniform4uiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniform4uiv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniform4uiv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLClearBufferiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLClearBufferiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLClearBufferiv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLClearBufferiv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLClearBufferuiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLClearBufferuiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLClearBufferuiv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLClearBufferuiv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLClearBufferfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLClearBufferfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLClearBufferfv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLClearBufferfv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLClearBufferfi
 * Signature: (IIFI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLClearBufferfi
  (JNIEnv *, jclass, jint, jint, jfloat, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetStringi
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES30Pipeline_nGLGetStringi
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLCopyBufferSubData
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLCopyBufferSubData
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetUniformIndices
 * Signature: (I[Ljava/lang/String;[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetUniformIndices__I_3Ljava_lang_String_2_3II
  (JNIEnv *, jclass, jint, jobjectArray, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetUniformIndices
 * Signature: (I[Ljava/lang/String;Ljava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetUniformIndices__I_3Ljava_lang_String_2Ljava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobjectArray, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetActiveUniformsiv
 * Signature: (II[III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetActiveUniformsiv__II_3III_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetActiveUniformsiv
 * Signature: (IILjava/nio/IntBuffer;IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetActiveUniformsiv__IILjava_nio_IntBuffer_2IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetUniformBlockIndex
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES30Pipeline_nGLGetUniformBlockIndex
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetActiveUniformBlockiv
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetActiveUniformBlockiv__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetActiveUniformBlockiv
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetActiveUniformBlockiv__IIILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetActiveUniformBlockName
 * Signature: (III[II[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetActiveUniformBlockName__III_3II_3BI
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetActiveUniformBlockName
 * Signature: (IIILjava/nio/Buffer;ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetActiveUniformBlockName__IIILjava_nio_Buffer_2ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetActiveUniformBlockName
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES30Pipeline_nGLGetActiveUniformBlockName__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLUniformBlockBinding
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLUniformBlockBinding
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDrawArraysInstanced
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDrawArraysInstanced
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDrawElementsInstanced
 * Signature: (IIILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDrawElementsInstanced__IIILjava_nio_Buffer_2II
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDrawElementsInstanced
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDrawElementsInstanced__IIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLFenceSync
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_gles_internal_GLES30Pipeline_nGLFenceSync
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLIsSync
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES30Pipeline_nGLIsSync
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDeleteSync
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDeleteSync
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLClientWaitSync
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES30Pipeline_nGLClientWaitSync
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLWaitSync
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLWaitSync
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetInteger64v
 * Signature: (I[JI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetInteger64v__I_3JI
  (JNIEnv *, jclass, jint, jlongArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetInteger64v
 * Signature: (ILjava/nio/LongBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetInteger64v__ILjava_nio_LongBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetSynciv
 * Signature: (JII[II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetSynciv__JII_3II_3II
  (JNIEnv *, jclass, jlong, jint, jint, jintArray, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetSynciv
 * Signature: (JIILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetSynciv__JIILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetInteger64iv
 * Signature: (II[JI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetInteger64iv__II_3JI
  (JNIEnv *, jclass, jint, jint, jlongArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetInteger64iv
 * Signature: (IILjava/nio/LongBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetInteger64iv__IILjava_nio_LongBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetBufferParameteri64v
 * Signature: (II[JI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetBufferParameteri64v__II_3JI
  (JNIEnv *, jclass, jint, jint, jlongArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetBufferParameteri64v
 * Signature: (IILjava/nio/LongBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetBufferParameteri64v__IILjava_nio_LongBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGenSamplers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGenSamplers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGenSamplers
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGenSamplers__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDeleteSamplers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDeleteSamplers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDeleteSamplers
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDeleteSamplers__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLIsSampler
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES30Pipeline_nGLIsSampler
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLBindSampler
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLBindSampler
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLSamplerParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLSamplerParameteri
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLSamplerParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLSamplerParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLSamplerParameteriv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLSamplerParameteriv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLSamplerParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLSamplerParameterf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLSamplerParameterfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLSamplerParameterfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLSamplerParameterfv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLSamplerParameterfv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetSamplerParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetSamplerParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetSamplerParameteriv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetSamplerParameteriv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetSamplerParameterfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetSamplerParameterfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetSamplerParameterfv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetSamplerParameterfv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLVertexAttribDivisor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLVertexAttribDivisor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLBindTransformFeedback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLBindTransformFeedback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDeleteTransformFeedbacks
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDeleteTransformFeedbacks__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLDeleteTransformFeedbacks
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLDeleteTransformFeedbacks__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGenTransformFeedbacks
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGenTransformFeedbacks__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGenTransformFeedbacks
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGenTransformFeedbacks__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLIsTransformFeedback
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES30Pipeline_nGLIsTransformFeedback
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLPauseTransformFeedback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLPauseTransformFeedback
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLResumeTransformFeedback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLResumeTransformFeedback
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetProgramBinary
 * Signature: (II[II[IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetProgramBinary__II_3II_3IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jintArray, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetProgramBinary
 * Signature: (IILjava/nio/IntBuffer;ILjava/nio/IntBuffer;ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetProgramBinary__IILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLProgramBinary
 * Signature: (IILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLProgramBinary
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLProgramParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLProgramParameteri
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLInvalidateFramebuffer
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLInvalidateFramebuffer__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLInvalidateFramebuffer
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLInvalidateFramebuffer__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLInvalidateSubFramebuffer
 * Signature: (II[IIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLInvalidateSubFramebuffer__II_3IIIIII
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLInvalidateSubFramebuffer
 * Signature: (IILjava/nio/IntBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLInvalidateSubFramebuffer__IILjava_nio_IntBuffer_2IIIII
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLTexStorage2D
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLTexStorage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLTexStorage3D
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLTexStorage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetInternalformativ
 * Signature: (IIII[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetInternalformativ__IIII_3II
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES30Pipeline
 * Method:    nGLGetInternalformativ
 * Signature: (IIIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES30Pipeline_nGLGetInternalformativ__IIIILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
