/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gles_internal_GLES11Pipeline */

#ifndef _Included_gles_internal_GLES11Pipeline
#define _Included_gles_internal_GLES11Pipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLES11ClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLES11ClassInit
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLBindBuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLBindBuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLBufferData
 * Signature: (IILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLBufferData__IILjava_nio_Buffer_2II
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLBufferData
 * Signature: (II[BII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLBufferData__II_3BII
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLBufferData
 * Signature: (II[SII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLBufferData__II_3SII
  (JNIEnv *, jclass, jint, jint, jshortArray, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLBufferData
 * Signature: (II[FII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLBufferData__II_3FII
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLBufferData
 * Signature: (II[III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLBufferData__II_3III
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLBufferSubData
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLBufferSubData__IIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLBufferSubData
 * Signature: (III[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLBufferSubData__III_3BI
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLBufferSubData
 * Signature: (III[SI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLBufferSubData__III_3SI
  (JNIEnv *, jclass, jint, jint, jint, jshortArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLBufferSubData
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLBufferSubData__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLBufferSubData
 * Signature: (III[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLBufferSubData__III_3FI
  (JNIEnv *, jclass, jint, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLClipPlanef
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLClipPlanef__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLClipPlanef
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLClipPlanef__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLClipPlanex
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLClipPlanex__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLClipPlanex
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLClipPlanex__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLColor4ub
 * Signature: (BBBB)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLColor4ub
  (JNIEnv *, jclass, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLColorPointer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLColorPointer
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLDeleteBuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLDeleteBuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLDeleteBuffers
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLDeleteBuffers__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLDrawElements
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLDrawElements
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGenBuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGenBuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGenBuffers
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGenBuffers__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetBooleanv
 * Signature: (I[ZI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetBooleanv__I_3ZI
  (JNIEnv *, jclass, jint, jbooleanArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetBooleanv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetBooleanv__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetBooleanv
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetBooleanv__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetBufferParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetBufferParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetBufferParameteriv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetBufferParameteriv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetClipPlanef
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetClipPlanef__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetClipPlanef
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetClipPlanef__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetClipPlanex
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetClipPlanex__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetClipPlanex
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetClipPlanex__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetFixedv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetFixedv__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetFixedv
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetFixedv__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetFloatv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetFloatv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetFloatv
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetFloatv__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetLightfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetLightfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetLightfv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetLightfv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetLightxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetLightxv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetLightxv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetLightxv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetMaterialfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetMaterialfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetMaterialfv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetMaterialfv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetMaterialxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetMaterialxv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetMaterialxv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetMaterialxv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetTexEnvfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetTexEnvfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetTexEnvfv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetTexEnvfv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetTexEnviv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetTexEnviv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetTexEnviv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetTexEnviv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetTexEnvxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetTexEnvxv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetTexEnvxv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetTexEnvxv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetTexParameterfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetTexParameterfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetTexParameterfv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetTexParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetTexParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetTexParameteriv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetTexParameterxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetTexParameterxv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLGetTexParameterxv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLGetTexParameterxv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLIsBuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES11Pipeline_nGLIsBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLIsEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES11Pipeline_nGLIsEnabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLIsTexture
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES11Pipeline_nGLIsTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLNormalPointer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLNormalPointer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLPointParameterf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLPointParameterf
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLPointParameterfv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLPointParameterfv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLPointParameterfv
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLPointParameterfv__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLPointParameterx
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLPointParameterx
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLPointParameterxv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLPointParameterxv__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLPointParameterxv
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLPointParameterxv__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLPointSizePointerOESBounds
 * Signature: (IILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLPointSizePointerOESBounds
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLTexCoordPointer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLTexCoordPointer
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLTexEnvi
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLTexEnvi
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLTexEnviv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLTexEnviv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLTexEnviv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLTexEnviv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLTexParameterfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLTexParameterfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLTexParameterfv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLTexParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLTexParameteri
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLTexParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLTexParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLTexParameteriv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLTexParameterxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLTexParameterxv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLTexParameterxv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLTexParameterxv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11Pipeline
 * Method:    nGLVertexPointer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11Pipeline_nGLVertexPointer
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
