/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gles_internal_GLES10Pipeline */

#ifndef _Included_gles_internal_GLES10Pipeline
#define _Included_gles_internal_GLES10Pipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLES10ClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLES10ClassInit
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLActiveTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLActiveTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLAlphaFunc
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLAlphaFunc
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLAlphaFuncx
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLAlphaFuncx
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLBindTexture
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLBindTexture
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLBlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLBlendFunc
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLClear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLClear
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLClearColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLClearColorx
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLClearColorx
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLClearDepthf
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLClearDepthf
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLClearDepthx
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLClearDepthx
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLClearStencil
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLClearStencil
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLClientActiveTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLClientActiveTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLColor4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLColor4f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLColor4x
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLColor4x
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLColorMask
 * Signature: (ZZZZ)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLColorMask
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLColorPointer
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLColorPointer
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLCompressedTexImage2D
 * Signature: (IIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLCompressedTexImage2D__IIIIIIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLCompressedTexImage2D
 * Signature: (IIIIIII[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLCompressedTexImage2D__IIIIIII_3BI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLCompressedTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLCompressedTexSubImage2D__IIIIIIIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLCompressedTexSubImage2D
 * Signature: (IIIIIIII[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLCompressedTexSubImage2D__IIIIIIII_3BI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLCopyTexImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLCopyTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLCopyTexSubImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLCopyTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLCullFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLCullFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLDeleteTextures
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLDeleteTextures__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLDeleteTextures
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLDeleteTextures__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLDepthFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLDepthFunc
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLDepthMask
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLDepthMask
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLDepthRangef
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLDepthRangef
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLDepthRangex
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLDepthRangex
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLDisable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLDisable
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLDisableClientState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLDisableClientState
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLDrawArrays
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLDrawArrays
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLDrawElements
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLDrawElements__IIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLDrawElements
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLDrawElements__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLDrawElements
 * Signature: (III[SI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLDrawElements__III_3SI
  (JNIEnv *, jclass, jint, jint, jint, jshortArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLDrawElements
 * Signature: (III[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLDrawElements__III_3BI
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLEnable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLEnable
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLEnableClientState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLEnableClientState
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLFinish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLFinish
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLFlush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLFlush
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLFogf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLFogf
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLFogfv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLFogfv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLFogfv
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLFogfv__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLFogx
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLFogx
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLFogxv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLFogxv__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLFogxv
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLFogxv__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLFrontFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLFrontFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLFrustumf
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLFrustumf
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLFrustumx
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLFrustumx
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLGenTextures
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLGenTextures__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLGenTextures
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLGenTextures__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLGetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES10Pipeline_nGLGetError
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLGetIntegerv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLGetIntegerv__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLGetIntegerv
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLGetIntegerv__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES10Pipeline_nGLGetString
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLHint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLightModelf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLightModelf
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLightModelfv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLightModelfv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLightModelfv
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLightModelfv__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLightModelx
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLightModelx
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLightModelxv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLightModelxv__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLightModelxv
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLightModelxv__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLightf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLightf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLightfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLightfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLightfv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLightfv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLightx
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLightx
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLightxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLightxv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLightxv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLightxv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLineWidth
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLineWidthx
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLineWidthx
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLoadIdentity
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLoadIdentity
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLoadMatrixf
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLoadMatrixf___3FI
  (JNIEnv *, jclass, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLoadMatrixf
 * Signature: (Ljava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLoadMatrixf__Ljava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLoadMatrixx
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLoadMatrixx___3II
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLoadMatrixx
 * Signature: (Ljava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLoadMatrixx__Ljava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLLogicOp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLLogicOp
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLMaterialf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLMaterialf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLMaterialfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLMaterialfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLMaterialfv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLMaterialfv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLMaterialx
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLMaterialx
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLMaterialxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLMaterialxv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLMaterialxv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLMaterialxv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLMatrixMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLMatrixMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLMultMatrixf
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLMultMatrixf___3FI
  (JNIEnv *, jclass, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLMultMatrixf
 * Signature: (Ljava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLMultMatrixf__Ljava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLMultMatrixx
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLMultMatrixx___3II
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLMultMatrixx
 * Signature: (Ljava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLMultMatrixx__Ljava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLMultiTexCoord4f
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLMultiTexCoord4f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLMultiTexCoord4x
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLMultiTexCoord4x
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLNormal3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLNormal3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLNormal3x
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLNormal3x
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLNormalPointerBounds
 * Signature: (IILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLNormalPointerBounds
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLOrthof
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLOrthof
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLOrthox
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLOrthox
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLPixelStorei
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLPixelStorei
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLPointSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLPointSize
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLPointSizex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLPointSizex
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLPolygonOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLPolygonOffset
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLPolygonOffsetx
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLPolygonOffsetx
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLPopMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLPopMatrix
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLPushMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLPushMatrix
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLReadPixels
 * Signature: (IIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLReadPixels__IIIIIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLReadPixels
 * Signature: (IIIIII[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLReadPixels__IIIIII_3BI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLRotatef
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLRotatef
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLRotatex
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLRotatex
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLSampleCoverage
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLSampleCoverage
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLSampleCoveragex
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLSampleCoveragex
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLScalef
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLScalef
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLScalex
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLScalex
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLScissor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLScissor
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLShadeModel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLShadeModel
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLStencilFunc
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLStencilFunc
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLStencilMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLStencilMask
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLStencilOp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLStencilOp
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexCoordPointerBounds
 * Signature: (IIILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexCoordPointerBounds
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexEnvf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexEnvf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexEnvfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexEnvfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexEnvfv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexEnvfv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexEnvx
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexEnvx
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexEnvxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexEnvxv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexEnvxv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexEnvxv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexImage2D__IIIIIIIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexImage2D
 * Signature: (IIIIIIII[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexImage2D__IIIIIIII_3BI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexImage2D
 * Signature: (IIIIIIII[SI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexImage2D__IIIIIIII_3SI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jshortArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexParameterf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexParameterx
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexParameterx
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexSubImage2D__IIIIIIIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexSubImage2D
 * Signature: (IIIIIIII[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexSubImage2D__IIIIIIII_3BI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTexSubImage2D
 * Signature: (IIIIIIII[SI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTexSubImage2D__IIIIIIII_3SI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jshortArray, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTranslatef
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTranslatef
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLTranslatex
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLTranslatex
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLVertexPointerBounds
 * Signature: (IIILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLVertexPointerBounds
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     gles_internal_GLES10Pipeline
 * Method:    nGLViewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES10Pipeline_nGLViewport
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
