/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gles_emulator_util_DrawingSurface */

#ifndef _Included_gles_emulator_util_DrawingSurface
#define _Included_gles_emulator_util_DrawingSurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gles_emulator_util_DrawingSurface
 * Method:    lock0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_emulator_util_DrawingSurface_lock0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gles_emulator_util_DrawingSurface
 * Method:    unlock0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_emulator_util_DrawingSurface_unlock0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
