/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gles_internal_GLES31Pipeline */

#ifndef _Included_gles_internal_GLES31Pipeline
#define _Included_gles_internal_GLES31Pipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLDispatchCompute
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLDispatchCompute
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLDispatchComputeIndirect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLDispatchComputeIndirect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLDrawArraysIndirect
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLDrawArraysIndirect
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLDrawElementsIndirect
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLDrawElementsIndirect
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLFramebufferParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLFramebufferParameteri
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetFramebufferParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetFramebufferParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetFramebufferParameteriv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetFramebufferParameteriv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetProgramInterfaceiv
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetProgramInterfaceiv__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetProgramInterfaceiv
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetProgramInterfaceiv__IIILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetProgramResourceIndex
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES31Pipeline_nGLGetProgramResourceIndex
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetProgramResourceName
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES31Pipeline_nGLGetProgramResourceName
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetProgramResourceiv
 * Signature: (IIII[III[II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetProgramResourceiv__IIII_3III_3II_3II
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray, jint, jint, jintArray, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetProgramResourceiv
 * Signature: (IIIILjava/nio/IntBuffer;IILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetProgramResourceiv__IIIILjava_nio_IntBuffer_2IILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject, jint, jint, jobject, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetProgramResourceLocation
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES31Pipeline_nGLGetProgramResourceLocation
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLUseProgramStages
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLUseProgramStages
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLActiveShaderProgram
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLActiveShaderProgram
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLCreateShaderProgramv
 * Signature: (II[Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES31Pipeline_nGLCreateShaderProgramv
  (JNIEnv *, jclass, jint, jint, jobjectArray, jboolean);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLBindProgramPipeline
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLBindProgramPipeline
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLDeleteProgramPipelines
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLDeleteProgramPipelines__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLDeleteProgramPipelines
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLDeleteProgramPipelines__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGenProgramPipelines
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGenProgramPipelines__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGenProgramPipelines
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGenProgramPipelines__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLIsProgramPipeline
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES31Pipeline_nGLIsProgramPipeline
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetProgramPipelineiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetProgramPipelineiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetProgramPipelineiv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetProgramPipelineiv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform1i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform1i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform2i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform2i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform3i
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform3i
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform4i
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform4i
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform1ui
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform1ui
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform2ui
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform2ui
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform3ui
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform3ui
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform4ui
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform4ui
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform1f
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform1f
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform2f
 * Signature: (IIFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform2f
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform3f
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform3f
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform4f
 * Signature: (IIFFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform4f
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform1iv
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform1iv__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform1iv
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform1iv__IIILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform2iv
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform2iv__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform2iv
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform2iv__IIILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform3iv
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform3iv__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform3iv
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform3iv__IIILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform4iv
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform4iv__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform4iv
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform4iv__IIILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform1uiv
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform1uiv__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform1uiv
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform1uiv__IIILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform2uiv
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform2uiv__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform2uiv
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform2uiv__IIILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform3uiv
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform3uiv__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform3uiv
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform3uiv__IIILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform4uiv
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform4uiv__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform4uiv
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform4uiv__IIILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform1fv
 * Signature: (III[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform1fv__III_3FI
  (JNIEnv *, jclass, jint, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform1fv
 * Signature: (IIILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform1fv__IIILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform2fv
 * Signature: (III[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform2fv__III_3FI
  (JNIEnv *, jclass, jint, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform2fv
 * Signature: (IIILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform2fv__IIILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform3fv
 * Signature: (III[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform3fv__III_3FI
  (JNIEnv *, jclass, jint, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform3fv
 * Signature: (IIILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform3fv__IIILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform4fv
 * Signature: (III[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform4fv__III_3FI
  (JNIEnv *, jclass, jint, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniform4fv
 * Signature: (IIILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniform4fv__IIILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix2fv
 * Signature: (IIIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix2fv__IIIZ_3FI
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix2fv
 * Signature: (IIIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix2fv__IIIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix3fv
 * Signature: (IIIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix3fv__IIIZ_3FI
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix3fv
 * Signature: (IIIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix3fv__IIIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix4fv
 * Signature: (IIIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix4fv__IIIZ_3FI
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix4fv
 * Signature: (IIIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix4fv__IIIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix2x3fv
 * Signature: (IIIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix2x3fv__IIIZ_3FI
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix2x3fv
 * Signature: (IIIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix2x3fv__IIIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix3x2fv
 * Signature: (IIIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix3x2fv__IIIZ_3FI
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix3x2fv
 * Signature: (IIIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix3x2fv__IIIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix2x4fv
 * Signature: (IIIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix2x4fv__IIIZ_3FI
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix2x4fv
 * Signature: (IIIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix2x4fv__IIIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix4x2fv
 * Signature: (IIIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix4x2fv__IIIZ_3FI
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix4x2fv
 * Signature: (IIIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix4x2fv__IIIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix3x4fv
 * Signature: (IIIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix3x4fv__IIIZ_3FI
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix3x4fv
 * Signature: (IIIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix3x4fv__IIIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix4x3fv
 * Signature: (IIIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix4x3fv__IIIZ_3FI
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLProgramUniformMatrix4x3fv
 * Signature: (IIIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLProgramUniformMatrix4x3fv__IIIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLValidateProgramPipeline
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLValidateProgramPipeline
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetProgramPipelineInfoLog
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES31Pipeline_nGLGetProgramPipelineInfoLog
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLBindImageTexture
 * Signature: (IIIZIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLBindImageTexture
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetBooleaniv
 * Signature: (II[ZI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetBooleaniv__II_3ZI
  (JNIEnv *, jclass, jint, jint, jbooleanArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetBooleaniv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetBooleaniv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLMemoryBarrier
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLMemoryBarrier
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLMemoryBarrierByRegion
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLMemoryBarrierByRegion
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLTexStorage2DMultisample
 * Signature: (IIIIIZ)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLTexStorage2DMultisample
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetMultisamplefv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetMultisamplefv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetMultisamplefv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetMultisamplefv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLSampleMaski
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLSampleMaski
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetTexLevelParameteriv
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetTexLevelParameteriv__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetTexLevelParameteriv
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetTexLevelParameteriv__IIILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetTexLevelParameterfv
 * Signature: (III[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetTexLevelParameterfv__III_3FI
  (JNIEnv *, jclass, jint, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLGetTexLevelParameterfv
 * Signature: (IIILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLGetTexLevelParameterfv__IIILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLBindVertexBuffer
 * Signature: (IIJI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLBindVertexBuffer
  (JNIEnv *, jclass, jint, jint, jlong, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLVertexAttribFormat
 * Signature: (IIIZI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLVertexAttribFormat
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLVertexAttribIFormat
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLVertexAttribIFormat
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLVertexAttribBinding
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLVertexAttribBinding
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES31Pipeline
 * Method:    nGLVertexBindingDivisor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES31Pipeline_nGLVertexBindingDivisor
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
