/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gles_internal_GLES20Pipeline */

#ifndef _Included_gles_internal_GLES20Pipeline
#define _Included_gles_internal_GLES20Pipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLES20ClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLES20ClassInit
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLActiveTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLActiveTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLAttachShader
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLAttachShader
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLBindAttribLocation
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLBindAttribLocation
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLBindBuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLBindBuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLBindFramebuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLBindFramebuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLBindRenderbuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLBindRenderbuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLBindTexture
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLBindTexture
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLBlendColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLBlendColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLBlendEquation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLBlendEquation
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLBlendEquationSeparate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLBlendEquationSeparate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLBlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLBlendFunc
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLBlendFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLBlendFuncSeparate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLBufferData
 * Signature: (IILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLBufferData
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLBufferSubData
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLBufferSubData
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLCheckFramebufferStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES20Pipeline_nGLCheckFramebufferStatus
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLClear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLClear
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLClearColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLClearDepthf
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLClearDepthf
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLClearStencil
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLClearStencil
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLColorMask
 * Signature: (ZZZZ)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLColorMask
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLCompileShader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLCompileShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLCompressedTexImage2D
 * Signature: (IIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLCompressedTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLCompressedTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLCompressedTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLCopyTexImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLCopyTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLCopyTexSubImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLCopyTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLCreateProgram
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES20Pipeline_nGLCreateProgram
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLCreateShader
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES20Pipeline_nGLCreateShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLCullFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLCullFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDeleteBuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDeleteBuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDeleteBuffers
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDeleteBuffers__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDeleteFramebuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDeleteFramebuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDeleteFramebuffers
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDeleteFramebuffers__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDeleteProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDeleteProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDeleteRenderbuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDeleteRenderbuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDeleteRenderbuffers
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDeleteRenderbuffers__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDeleteShader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDeleteShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDeleteTextures
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDeleteTextures__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDeleteTextures
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDeleteTextures__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDepthFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDepthFunc
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDepthMask
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDepthMask
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDepthRangef
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDepthRangef
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDetachShader
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDetachShader
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDisable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDisable
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDisableVertexAttribArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDisableVertexAttribArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDrawArrays
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDrawArrays
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDrawElements
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDrawElements__IIII
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLDrawElements
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLDrawElements__IIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLEnable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLEnable
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLEnableVertexAttribArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLEnableVertexAttribArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLFinish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLFinish
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLFlush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLFlush
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLFramebufferRenderbuffer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLFramebufferRenderbuffer
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLFramebufferTexture2D
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLFramebufferTexture2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLFrontFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLFrontFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGenBuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGenBuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGenBuffers
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGenBuffers__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGenerateMipmap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGenerateMipmap
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGenFramebuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGenFramebuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGenFramebuffers
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGenFramebuffers__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGenRenderbuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGenRenderbuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGenRenderbuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGenRenderbuffers__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGenTextures
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGenTextures__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGenTextures
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGenTextures__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetActiveAttrib
 * Signature: (III[II[II[II[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetActiveAttrib__III_3II_3II_3II_3BI
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint, jintArray, jint, jintArray, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetActiveAttrib
 * Signature: (IIILjava/nio/IntBuffer;Ljava/nio/IntBuffer;Ljava/nio/IntBuffer;B)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetActiveAttrib__IIILjava_nio_IntBuffer_2Ljava_nio_IntBuffer_2Ljava_nio_IntBuffer_2B
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject, jobject, jbyte);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetActiveAttrib
 * Signature: (II[II[II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES20Pipeline_nGLGetActiveAttrib__II_3II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetActiveAttrib
 * Signature: (IILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES20Pipeline_nGLGetActiveAttrib__IILjava_nio_IntBuffer_2ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetActiveUniform
 * Signature: (III[II[II[II[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetActiveUniform__III_3II_3II_3II_3BI
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint, jintArray, jint, jintArray, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetActiveUniform
 * Signature: (II[II[II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES20Pipeline_nGLGetActiveUniform__II_3II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetActiveUniform
 * Signature: (IILjava/nio/IntBuffer;Ljava/nio/IntBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES20Pipeline_nGLGetActiveUniform__IILjava_nio_IntBuffer_2Ljava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetAttachedShaders
 * Signature: (II[II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetAttachedShaders__II_3II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetAttachedShaders
 * Signature: (IILjava/nio/IntBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetAttachedShaders__IILjava_nio_IntBuffer_2Ljava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetAttribLocation
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES20Pipeline_nGLGetAttribLocation
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetBooleanv
 * Signature: (I[ZI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetBooleanv__I_3ZI
  (JNIEnv *, jclass, jint, jbooleanArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetBooleanv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetBooleanv__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetBufferParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetBufferParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetBufferParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetBufferParameteriv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES20Pipeline_nGLGetError
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetFloatv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetFloatv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetFloatv
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetFloatv__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetFramebufferAttachmentParameteriv
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetFramebufferAttachmentParameteriv__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetFramebufferAttachmentParameteriv
 * Signature: (IIILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetFramebufferAttachmentParameteriv__IIILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetIntegerv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetIntegerv__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetIntegerv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetIntegerv__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetProgramiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetProgramiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetProgramiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetProgramiv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetProgramInfoLog
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES20Pipeline_nGLGetProgramInfoLog
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetRenderbufferParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetRenderbufferParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetRenderbufferParameteriv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetRenderbufferParameteriv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetShaderiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetShaderiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetShaderiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetShaderiv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetShaderInfoLog
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES20Pipeline_nGLGetShaderInfoLog
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetShaderPrecisionFormat
 * Signature: (II[II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetShaderPrecisionFormat__II_3II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetShaderPrecisionFormat
 * Signature: (IILjava/nio/IntBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetShaderPrecisionFormat__IILjava_nio_IntBuffer_2Ljava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetShaderSource
 * Signature: (II[II[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetShaderSource__II_3II_3BI
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetShaderSource
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES20Pipeline_nGLGetShaderSource__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gles_internal_GLES20Pipeline_nGLGetString
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetTexParameterfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetTexParameterfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetTexParameterfv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetTexParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetTexParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetTexParameteriv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetUniformfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetUniformfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetUniformfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetUniformfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetUniformiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetUniformiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetUniformiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetUniformiv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetUniformLocation
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES20Pipeline_nGLGetUniformLocation
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetVertexAttribfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetVertexAttribfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetVertexAttribfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetVertexAttribfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetVertexAttribiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetVertexAttribiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLGetVertexAttribiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLGetVertexAttribiv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLHint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLIsBuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES20Pipeline_nGLIsBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLIsEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES20Pipeline_nGLIsEnabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLIsFramebuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES20Pipeline_nGLIsFramebuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLIsProgram
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES20Pipeline_nGLIsProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLIsRenderbuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES20Pipeline_nGLIsRenderbuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLIsShader
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES20Pipeline_nGLIsShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLIsTexture
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES20Pipeline_nGLIsTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLLineWidth
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLLinkProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLLinkProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLPixelStorei
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLPixelStorei
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLPolygonOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLPolygonOffset
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLReadPixels
 * Signature: (IIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLReadPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLReleaseShaderCompiler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLReleaseShaderCompiler
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLRenderbufferStorage
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLRenderbufferStorage
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLSampleCoverage
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLSampleCoverage
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLScissor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLScissor
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLShaderBinary
 * Signature: (I[IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLShaderBinary__I_3IIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jintArray, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLShaderBinary
 * Signature: (ILjava/nio/IntBuffer;ILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLShaderBinary__ILjava_nio_IntBuffer_2ILjava_nio_Buffer_2II
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLShaderSource
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLShaderSource
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLStencilFunc
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLStencilFunc
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLStencilFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLStencilFuncSeparate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLStencilMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLStencilMask
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLStencilMaskSeparate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLStencilMaskSeparate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLStencilOp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLStencilOp
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLStencilOpSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLStencilOpSeparate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLTexImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLTexParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLTexParameterf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLTexParameterfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLTexParameterfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLTexParameterfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLTexParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLTexParameteri
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLTexParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLTexParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLTexParameteriv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform1f
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform1f
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform1fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform1fv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform1fv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform1fv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform1i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform1i
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform1iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform1iv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform1iv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform1iv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform2f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform2f
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform2fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform2fv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform2fv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform2fv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform2i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform2i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform2iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform2iv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform2iv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform2iv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform3f
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform3f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform3fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform3fv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform3fv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform3fv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform3i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform3i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform3iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform3iv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform3iv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform3iv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform4f
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform4f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform4fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform4fv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform4fv
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform4fv__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform4i
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform4i
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform4iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform4iv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniform4iv
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniform4iv__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniformMatrix2fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniformMatrix2fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniformMatrix2fv
 * Signature: (IIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniformMatrix2fv__IIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniformMatrix3fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniformMatrix3fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniformMatrix3fv
 * Signature: (IIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniformMatrix3fv__IIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniformMatrix4fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniformMatrix4fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUniformMatrix4fv
 * Signature: (IIZLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUniformMatrix4fv__IIZLjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jboolean, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLUseProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLUseProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLValidateProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLValidateProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttrib1f
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttrib1f
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttrib1fv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttrib1fv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttrib1fv
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttrib1fv__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttrib2f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttrib2f
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttrib2fv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttrib2fv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttrib2fv
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttrib2fv__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttrib3f
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttrib3f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttrib3fv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttrib3fv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttrib3fv
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttrib3fv__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttrib4f
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttrib4f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttrib4fv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttrib4fv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttrib4fv
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttrib4fv__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttribPointer
 * Signature: (IIIZII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttribPointer
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLVertexAttribPointerBounds
 * Signature: (IIIZILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLVertexAttribPointerBounds
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES20Pipeline
 * Method:    nGLViewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES20Pipeline_nGLViewport
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
