/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gles_emulator_util_DrawingSurfaceInfo */

#ifndef _Included_gles_emulator_util_DrawingSurfaceInfo
#define _Included_gles_emulator_util_DrawingSurfaceInfo
#ifdef __cplusplus
extern "C" {
#endif
#undef gles_emulator_util_DrawingSurfaceInfo_EGLNativeDisplayType_index
#define gles_emulator_util_DrawingSurfaceInfo_EGLNativeDisplayType_index 0L
#undef gles_emulator_util_DrawingSurfaceInfo_EGLNativePixmapType_index
#define gles_emulator_util_DrawingSurfaceInfo_EGLNativePixmapType_index 1L
#undef gles_emulator_util_DrawingSurfaceInfo_EGLNativeWindowType_index
#define gles_emulator_util_DrawingSurfaceInfo_EGLNativeWindowType_index 2L
/*
 * Class:     gles_emulator_util_DrawingSurfaceInfo
 * Method:    updateEGLhandlers0
 * Signature: (JJ[J)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_emulator_util_DrawingSurfaceInfo_updateEGLhandlers0
  (JNIEnv *, jclass, jlong, jlong, jlongArray);

/*
 * Class:     gles_emulator_util_DrawingSurfaceInfo
 * Method:    getRectangle0
 * Signature: (JJ[I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_emulator_util_DrawingSurfaceInfo_getRectangle0
  (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     gles_emulator_util_DrawingSurfaceInfo
 * Method:    getHWND
 * Signature: (JJ[J)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_emulator_util_DrawingSurfaceInfo_getHWND
  (JNIEnv *, jclass, jlong, jlong, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
