/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gles_internal_GLES11ExtPipeline */

#ifndef _Included_gles_internal_GLES11ExtPipeline
#define _Included_gles_internal_GLES11ExtPipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLES11ExtClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLES11ExtClassInit
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLBlendEquationSeparateOES
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLBlendEquationSeparateOES
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLBlendFuncSeparateOES
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLBlendFuncSeparateOES
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLBlendEquationOES
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLBlendEquationOES
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDrawTexsOES
 * Signature: (SSSSS)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDrawTexsOES
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort, jshort);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDrawTexiOES
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDrawTexiOES
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDrawTexxOES
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDrawTexxOES
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDrawTexsvOES
 * Signature: ([SI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDrawTexsvOES___3SI
  (JNIEnv *, jclass, jshortArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDrawTexsvOES
 * Signature: (Ljava/nio/ShortBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDrawTexsvOES__Ljava_nio_ShortBuffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDrawTexivOES
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDrawTexivOES___3II
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDrawTexivOES
 * Signature: (Ljava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDrawTexivOES__Ljava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDrawTexxvOES
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDrawTexxvOES___3II
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDrawTexxvOES
 * Signature: (Ljava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDrawTexxvOES__Ljava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDrawTexfOES
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDrawTexfOES
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDrawTexfvOES
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDrawTexfvOES___3FI
  (JNIEnv *, jclass, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDrawTexfvOES
 * Signature: (Ljava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDrawTexfvOES__Ljava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLEGLImageTargetTexture2DOES
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLEGLImageTargetTexture2DOES__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLEGLImageTargetTexture2DOES
 * Signature: (I[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLEGLImageTargetTexture2DOES__I_3BI
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLEGLImageTargetTexture2DOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLEGLImageTargetTexture2DOES__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLEGLImageTargetTexture2DOES
 * Signature: (I[SI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLEGLImageTargetTexture2DOES__I_3SI
  (JNIEnv *, jclass, jint, jshortArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLEGLImageTargetRenderbufferStorageOES
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLEGLImageTargetRenderbufferStorageOES__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLEGLImageTargetRenderbufferStorageOES
 * Signature: (I[BI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLEGLImageTargetRenderbufferStorageOES__I_3BI
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLEGLImageTargetRenderbufferStorageOES
 * Signature: (I[SI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLEGLImageTargetRenderbufferStorageOES__I_3SI
  (JNIEnv *, jclass, jint, jshortArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLEGLImageTargetRenderbufferStorageOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLEGLImageTargetRenderbufferStorageOES__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLAlphaFuncxOES
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLAlphaFuncxOES
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLClearColorxOES
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLClearColorxOES
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLClearDepthxOES
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLClearDepthxOES
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLClipPlanexOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLClipPlanexOES__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLClipPlanexOES
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLClipPlanexOES__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLColor4xOES
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLColor4xOES
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDepthRangexOES
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDepthRangexOES
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLFogxOES
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLFogxOES
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLFogxvOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLFogxvOES__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLFogxvOES
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLFogxvOES__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLFrustumxOES
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLFrustumxOES
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetClipPlanexOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetClipPlanexOES__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetClipPlanexOES
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetClipPlanexOES__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetFixedvOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetFixedvOES__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetFixedvOES
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetFixedvOES__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetLightxvOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetLightxvOES__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetLightxvOES
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetLightxvOES__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetMaterialxvOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetMaterialxvOES__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetMaterialxvOES
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetMaterialxvOES__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetTexEnvxvOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetTexEnvxvOES__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetTexEnvxvOES
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetTexEnvxvOES__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetTexParameterxvOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetTexParameterxvOES__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetTexParameterxvOES
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetTexParameterxvOES__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLLightModelxOES
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLLightModelxOES
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLLightModelxvOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLLightModelxvOES__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLLightModelxvOES
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLLightModelxvOES__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLLightxOES
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLLightxOES
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLLightxvOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLLightxvOES__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLLightxvOES
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLLightxvOES__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLLineWidthxOES
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLLineWidthxOES
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLLoadMatrixxOES
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLLoadMatrixxOES___3II
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLLoadMatrixxOES
 * Signature: (Ljava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLLoadMatrixxOES__Ljava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLMaterialxOES
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLMaterialxOES
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLMaterialxvOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLMaterialxvOES__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLMaterialxvOES
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLMaterialxvOES__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLMultMatrixxOES
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLMultMatrixxOES___3II
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLMultMatrixxOES
 * Signature: (Ljava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLMultMatrixxOES__Ljava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLMultiTexCoord4xOES
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLMultiTexCoord4xOES
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLNormal3xOES
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLNormal3xOES
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLOrthoxOES
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLOrthoxOES
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLPointParameterxOES
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLPointParameterxOES
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLPointParameterxvOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLPointParameterxvOES__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLPointParameterxvOES
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLPointParameterxvOES__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLPointSizexOES
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLPointSizexOES
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLPolygonOffsetxOES
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLPolygonOffsetxOES
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLRotatexOES
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLRotatexOES
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLSampleCoveragexOES
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLSampleCoveragexOES
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLScalexOES
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLScalexOES
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexEnvxOES
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexEnvxOES
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexEnvxvOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexEnvxvOES__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexEnvxvOES
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexEnvxvOES__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexParameterxOES
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexParameterxOES
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexParameterxvOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexParameterxvOES__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexParameterxvOES
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexParameterxvOES__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTranslatexOES
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTranslatexOES
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLIsRenderbufferOES
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES11ExtPipeline_nGLIsRenderbufferOES
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLBindRenderbufferOES
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLBindRenderbufferOES
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDeleteRenderbuffersOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDeleteRenderbuffersOES__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDeleteRenderbuffersOES
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDeleteRenderbuffersOES__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGenRenderbuffersOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGenRenderbuffersOES__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGenRenderbuffersOES
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGenRenderbuffersOES__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLRenderbufferStorageOES
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLRenderbufferStorageOES
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetRenderbufferParameterivOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetRenderbufferParameterivOES__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetRenderbufferParameterivOES
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetRenderbufferParameterivOES__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLIsFramebufferOES
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gles_internal_GLES11ExtPipeline_nGLIsFramebufferOES
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLBindFramebufferOES
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLBindFramebufferOES
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDeleteFramebuffersOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDeleteFramebuffersOES__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDeleteFramebuffersOES
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDeleteFramebuffersOES__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGenFramebuffersOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGenFramebuffersOES__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGenFramebuffersOES
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGenFramebuffersOES__ILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLCheckFramebufferStatusOES
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gles_internal_GLES11ExtPipeline_nGLCheckFramebufferStatusOES
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLFramebufferRenderbufferOES
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLFramebufferRenderbufferOES
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLFramebufferTexture2DOES
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLFramebufferTexture2DOES
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetFramebufferAttachmentParameterivOES
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetFramebufferAttachmentParameterivOES__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetFramebufferAttachmentParameterivOES
 * Signature: (IIILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetFramebufferAttachmentParameterivOES__IIILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGenerateMipmapOES
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGenerateMipmapOES
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLCurrentPaletteMatrixOES
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLCurrentPaletteMatrixOES
  (JNIEnv *, jclass, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLLoadPaletteFromModelViewMatrixOES
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLLoadPaletteFromModelViewMatrixOES
  (JNIEnv *, jclass);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLMatrixIndexPointerOES
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLMatrixIndexPointerOES
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLMatrixIndexPointerOESBounds
 * Signature: (IIILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLMatrixIndexPointerOESBounds
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLWeightPointerOESBounds
 * Signature: (IIILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLWeightPointerOESBounds
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLDepthRangefOES
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLDepthRangefOES
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLFrustumfOES
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLFrustumfOES
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLOrthofOES
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLOrthofOES
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLClipPlanefOES
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLClipPlanefOES__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLClipPlanefOES
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLClipPlanefOES__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetClipPlanefOES
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetClipPlanefOES__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetClipPlanefOES
 * Signature: (ILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetClipPlanefOES__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLClearDepthfOES
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLClearDepthfOES
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexGenfOES
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexGenfOES
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexGenfvOES
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexGenfvOES__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexGenfvOES
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexGenfvOES__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexGeniOES
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexGeniOES
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexGenivOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexGenivOES__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexGenivOES
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexGenivOES__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexGenxOES
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexGenxOES
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexGenxvOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexGenxvOES__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLTexGenxvOES
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLTexGenxvOES__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetTexGenfvOES
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetTexGenfvOES__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetTexGenfvOES
 * Signature: (IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetTexGenfvOES__IILjava_nio_FloatBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetTexGenivOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetTexGenivOES__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetTexGenivOES
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetTexGenivOES__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetTexGenxvOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetTexGenxvOES__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     gles_internal_GLES11ExtPipeline
 * Method:    nGLGetTexGenxvOES
 * Signature: (IILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_gles_internal_GLES11ExtPipeline_nGLGetTexGenxvOES__IILjava_nio_IntBuffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
