/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gles_internal_TesteGL */

#ifndef _Included_gles_internal_TesteGL
#define _Included_gles_internal_TesteGL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gles_internal_TesteGL
 * Method:    nGLVertexAttrib1fv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_gles_internal_TesteGL_nGLVertexAttrib1fv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     gles_internal_TesteGL
 * Method:    nGLVertexAttrib2f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_gles_internal_TesteGL_nGLVertexAttrib2f
  (JNIEnv *, jclass, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
