/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class examples_Adder */

#ifndef _Included_examples_Adder
#define _Included_examples_Adder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     examples_Adder
 * Method:    add
 * Signature: ([FIIF)V
 */
JNIEXPORT void JNICALL Java_examples_Adder_add
  (JNIEnv *, jclass, jfloatArray, jint, jint, jfloat);

/*
 * Class:     examples_Adder
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_examples_Adder_print
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
